apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: webapp-demo
type: Opaque
data:
  # Проверьте, что URI правильный: mongodb://admin:password123@mongodb:27017/tasksdb?authSource=admin
  # echo -n "mongodb://admin:password123@mongodb:27017/tasksdb?authSource=admin" | base64
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTcvdGFza3NkYj9hdXRoU291cmNlPWFkbWlu