apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
  namespace: todo-app
type: Opaque
data:
  # Генерация: echo -n 'my-secret-key-123' | base64
  SESSION_SECRET: "bXktc2VjcmV0LWtleS0xMjM="