apiVersion: v1
kind: Service
metadata:
  name: todo-mongodb
  namespace: todo-app
  labels:
    app: todo-mongodb
    component: database
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: todo-mongodb
  clusterIP: None