apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: file-sharing
  labels:
    app: mongodb
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        component: database
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        args:
        - "--bind_ip_all"
        - "--quiet"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-init
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mongo  # ИСПРАВЛЕНО: было mongosh, теперь mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mongodb-data
        emptyDir:  # ✅ emptyDir НАСТРОЕН
          sizeLimit: 5Gi
      - name: mongodb-init
        configMap:
          name: mongodb-init-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: file-sharing
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP