apiVersion: v1
kind: Service
metadata:
  name: backend-monitor
  namespace: nightmare-project
  labels:
    app: backend
    monitor: "true"
spec:
  selector:
    app: sqlite-backend
  ports:
  - port: 5000
    targetPort: 5000
    name: http-metrics
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-monitor
  namespace: nightmare-project
  labels:
    app: frontend
    monitor: "true"
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-test-config
  namespace: nightmare-project
data:
  test-nodeport.sh: |
    #!/bin/bash
    NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
    
    echo "Testing http://$NODE_IP:30080"
    echo "================================"
    
    test_endpoint() {
        local url=$1
        local name=$2
        local response=$(curl -s -o /dev/null -w "%{http_code} %{time_total}s" "$url")
        echo "$name: $response"
    }
    
    test_endpoint "http://$NODE_IP:30080/health" "Frontend Health"
    test_endpoint "http://$NODE_IP:30080/api/health" "Backend Health"
    test_endpoint "http://$NODE_IP:30080/api/tasks" "Tasks API"
    
    echo -e "\nCORS Test:"
    curl -s -X OPTIONS "http://$NODE_IP:30080/api/tasks" \
      -H "Origin: http://example.com" \
      -H "Access-Control-Request-Method: GET" \
      -H "Access-Control-Request-Headers: X-Requested-With" \
      -I | grep -i "access-control"